// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using icarus.estoque.Data;

#nullable disable

namespace icarus.estoque.Migrations
{
    [DbContext(typeof(DataContextEstoque))]
    [Migration("20230522162946_NovosCampos")]
    partial class NovosCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("icarus.estoque.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("icarus.estoque.Models.Produto", b =>
                {
                    b.OwnsOne("icarus.estoque.Models.ValueObjects.Coloracao", "Cor", b1 =>
                        {
                            b1.Property<int>("ProdutoId")
                                .HasColumnType("int");

                            b1.Property<string>("Cor")
                                .HasColumnType("longtext")
                                .HasColumnName("Coloracao");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.OwnsOne("icarus.estoque.Models.ValueObjects.Quantidade", "QuantidadeProduto", b1 =>
                        {
                            b1.Property<int>("ProdutoId")
                                .HasColumnType("int");

                            b1.Property<int>("QuantidadeItem")
                                .HasColumnType("int")
                                .HasColumnName("QuantidadeEmEstoque");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.OwnsOne("icarus.estoque.Models.ValueObjects.Valor", "ValorUnitario", b1 =>
                        {
                            b1.Property<int>("ProdutoId")
                                .HasColumnType("int");

                            b1.Property<double>("ValorDoItem")
                                .HasColumnType("double")
                                .HasColumnName("ValorDoItem");

                            b1.HasKey("ProdutoId");

                            b1.ToTable("Produtos");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.Navigation("Cor");

                    b.Navigation("QuantidadeProduto")
                        .IsRequired();

                    b.Navigation("ValorUnitario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
